Renamed "banned" user status to "kicked"
ayrat555/frankenstein pull request #107
Opened 2023-05-11 20:07 UTC by lucacuzzocrea

Re-applied an old bug fix: #78 
Without this, get_updates fails to parse the response if it contains a "kicked" user. This makes the program unable to read any updates.

2023-05-11 20:52 UTC, EdJoPaTo commented
Is it kicked or banned in the documentation? The PR changes it so it’s not banned anymore. Would be better if it’s working for both while it’s named after the one in the documentation.

2023-05-11 21:05 UTC, Greganthon requested changes
no relevant

2023-05-11 21:06 UTC, Greganthon commented
Kindly respond to this message for assistance

2023-05-12 07:45 UTC, ayrat555 commented
@lucacuzzocrea @Greganthon can it be that you're running an old version of  Telegram Bot API server?

2023-05-12 08:41 UTC, lucacuzzocrea commented
> @lucacuzzocrea @Greganthon can it be that you're running an old version of Telegram Bot API server?

I'm using the public API server: https://api.telegram.org

2023-05-12 08:44 UTC, Greganthon commented
The AI bot are under maintenance right now

2023-09-29 07:12 UTC, ayrat555 commented
closed due inactivity

2023-09-29 07:12 UTC, closed without merging