feat: Ability to sendDocument formed from bytes
ayrat555/frankenstein pull request #108
Opened 2023-05-16 16:05 UTC by akahan

2023-05-20 17:18 UTC, ayrat555 reviewed
looking ok to me

@EdJoPaTo @pxp9 can you please check also

2023-05-20 17:18 UTC, ayrat555 commented on src/lib.rs
> +// pub use objects::*;
can you please revert this change

2023-05-20 17:18 UTC, ayrat555 commented on src/api/telegram_api_impl.rs
> +    use super::*;
can you please revert this change

2023-05-21 18:01 UTC, EdJoPaTo requested changes
I like seeing the creation of a File via Buffer instead of a file on disk!

There is a bunch if clippy hints and @ayrat555 also suggested some things I would suggest too.

There is also a lot of seemingly unrelated change, mainly code formatting which should be its own PQ to simplify reviewing of the concise change of creating `File` from bytes.

2023-05-22 23:31 UTC, akahan commented on src/lib.rs
> +// pub use objects::*;
ok. but `#[warn(ambiguous_glob_reexports)]` on by default.

2023-06-14 09:54 UTC, EdJoPaTo requested changes
There are still some linter hints which should be fixed. Also this PR will probably have merge conflicts with #109 as both are file related?

2023-09-29 07:12 UTC, ayrat555 commented
closed due inactivity

2023-09-29 07:12 UTC, closed without merging