API 7.4
ayrat555/frankenstein pull request #171
Opened 2024-06-17 18:54 UTC by ayrat555

2024-06-17 21:56 UTC, EdJoPaTo approved these changes
Haven't looked into the Bot API news, only the source code here which looks fine while scrolling over it.

2024-06-17 21:56 UTC, EdJoPaTo commented on src/api_params.rs
> +    pub show_caption_above_media: Option<bool>,
Unrelated thought sparked while looking into to this PR: Couldn't these parameters be `bool` instead of `Option<bool>`? The default would be false and always skipped and only when actively set to true be used? Not sure whether that's correct for all the bools.

2024-06-18 08:43 UTC, pxp9 commented on src/api_params.rs
>      #[builder(setter(into, strip_option), default)]
I think `InputMediaVideo` struct should be in `objects.rs` file since all Telegram classes are there.

Same with `InputMediaAnimation` and `InputMediaPhoto`.

2024-06-18 08:54 UTC, pxp9 requested changes
Nice work, I just have 1 question.

Why `InputMediaAnimation`, `InputMediaPhoto` and `InputMediaVideo` are in api_params instead of `objects.rs` ?

2024-06-18 08:57 UTC, pxp9 commented on src/api_params.rs
> +    pub show_caption_above_media: Option<bool>,
I think it is better to just leave it as `Option<bool>` because we might have `serde` parsing errors if we receive a json response without this field.

2024-06-18 09:01 UTC, pxp9 commented on src/api_params.rs
> +    pub show_caption_above_media: Option<bool>,
Also Telegram spec says explicitly that this params are optional.

2024-06-18 09:15 UTC, pxp9 approved these changes
LGTM

2024-06-18 09:51 UTC, EdJoPaTo commented on src/api_params.rs
> +    pub show_caption_above_media: Option<bool>,
> because we might have `serde` parsing errors if we receive a json response without this field.

There is `serde(default)` for that (would default to false)

2024-06-18 18:46 UTC, ayrat555 commented on src/api_params.rs
> +    pub show_caption_above_media: Option<bool>,
good catch. ideally we should do for all boolean values I think. will leave it like this for now

2024-06-18 18:46 UTC, merged