make allowed_update type safe
ayrat555/frankenstein pull request #65
Opened 2022-05-10 10:05 UTC by johannesvollmer

instead of having string values, use json to generate strings from a fixed set of enum values

2022-05-10 10:21 UTC, EdJoPaTo requested changes
I think the examples should not contain the allowed updates. The examples are meant to be simple, not to confuse with additional stuff to think about.

I would remove them from the examples.

2022-05-10 10:21 UTC, EdJoPaTo commented on src/objects.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
No need for references with `Copy`
```suggestion
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
```

2022-05-10 10:21 UTC, EdJoPaTo commented on src/objects.rs
> +pub enum AllowedUpdate {
Maybe mark this enum as `#[non_exhaustive]`?

(Maybe that might be good for some more enums in this crate?

2022-05-10 14:53 UTC, ayrat555 commented
@johannesvollmer your suggestion makes sense. and the pr looks good to me

when @EdJoPaTo approves we can merge

2022-05-10 17:06 UTC, EdJoPaTo commented
> We can simplify the examples like this

Looks good. Lets get rid of the `allowed_updates` in the examples.

2022-05-10 17:18 UTC, johannesvollmer commented
Although, I would recommend to add separate more sophisticated examples later. Especially for people understanding Rust, but with less experience in using the Telegram API. For me, after reading the example, I understood what the `GetUpdatsParams.offset` field is supposed to do

2022-05-10 19:14 UTC, EdJoPaTo approved these changes

2022-05-11 06:37 UTC, merged

2022-05-11 06:48 UTC, ayrat555 commented
Thank you for your work, guys. We should move the library to the organisation (so it won't be associated only with me). But it seems it's overhead to create an organisation for a simple library. 

At least I need to remove my sponsor links from the library

2022-05-11 06:55 UTC, johannesvollmer commented
You two could do it, but for me it's fine as-is :)

2022-05-11 07:44 UTC, EdJoPaTo commented
Nah, keep it as it is. No need for organizations for everything. You can also keep the sponsoring stuff if you want to. I am fine with one person in there while others are helping.
(Which reminds me: I should continue setting up my sponsor stuff sometime…)