August 12 most api changes
ayrat555/frankenstein pull request #85
Opened 2022-08-12 15:45 UTC by pxp9

2022-08-12 15:46 UTC, pxp9 commented
Not finished yet

2022-08-12 22:57 UTC, pxp9 commented on src/objects.rs
> -    pub contains_masks: bool,
Maybe we should put in some way this is deprecated, but when i put that i got errors in the test and also i got a warning so for now i delete it.

2022-08-12 23:03 UTC, pxp9 commented on src/objects.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
I make two enum types for Stickers because they not serialize in the same way, take a look
```rust
#[serde(rename = "type")]
pub enum StickerType {
```
```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename = "sticker_type")]
pub enum StickerTypeSet {
```

2022-08-12 23:09 UTC, pxp9 commented on src/objects.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
Solve in [Just one StickerType](https://github.com/ayrat555/frankenstein/pull/85/commits/cf99e3a754fd53f19a291130ce292da8ce326cf0)

2022-08-13 06:50 UTC, ayrat555 requested changes
Added some comments

plus the following changes are not implemented 
![Screenshot 2022-08-13 at 09 49 25](https://user-images.githubusercontent.com/6567687/184472401-1c532b28-40a7-4354-8c45-92ebf23d682c.png)

2022-08-13 06:50 UTC, ayrat555 commented on src/objects.rs
> +    CustomEmoji,
1. Added the [MessageEntity](https://core.telegram.org/bots/api#messageentity) type “custom_emoji”.

looks good!

2022-08-13 06:50 UTC, ayrat555 commented on src/objects.rs
> +    pub custom_emoji_id: Option<String>,
2. Added the field custom_emoji_id to the class [MessageEntity](https://core.telegram.org/bots/api#messageentity) for “custom_emoji” entities.

Looks good!

2022-08-13 06:50 UTC, ayrat555 commented on src/api_params.rs
> +    #[builder(setter(into, strip_option), default=Some(StickerType::Regular))]
let's remove a default value. default is None

2022-08-13 06:50 UTC, ayrat555 commented on src/api_traits/async_telegram_api.rs
> +    ) -> Result<MethodResponse<bool>, Self::Error> {
return type not bool but

```
Returns an Array of [Sticker](https://core.telegram.org/bots/api#sticker) objects.
```

2022-08-13 06:50 UTC, ayrat555 commented on src/objects.rs
> +pub enum StickerType {
let's add this enum before each struct in this file

2022-08-13 06:50 UTC, ayrat555 commented on src/objects.rs
> -    pub contains_masks: bool,
let's not delete this field.

2022-08-13 07:03 UTC, pxp9 commented on src/objects.rs
> +    CustomEmoji,
Nice

2022-08-13 07:03 UTC, pxp9 commented on src/objects.rs
> +    pub custom_emoji_id: Option<String>,
Nice

2022-08-13 07:06 UTC, pxp9 commented on src/objects.rs
> +    pub has_restricted_voice_and_video_messages: Option<bool>,
Other Changes Done :D

2022-08-13 07:09 UTC, ayrat555 commented on src/objects.rs
> -    pub contains_masks: bool,
it should be possible to use

https://doc.bccnsoft.com/docs/rust-1.36.0-docs-html/edition-guide/rust-2018/the-compiler/an-attribute-for-deprecation.html

2022-08-13 07:33 UTC, pxp9 commented on src/objects.rs
> +pub enum StickerType {
Solve in [Fix comments](https://github.com/ayrat555/frankenstein/pull/85/commits/162f8477c136b3510ed3576cbf436881b603e47b)

2022-08-13 07:34 UTC, pxp9 commented on src/objects.rs
> -    pub contains_masks: bool,
Added as deprecated in [Fix comments](https://github.com/ayrat555/frankenstein/pull/85/commits/162f8477c136b3510ed3576cbf436881b603e47b)

2022-08-13 07:34 UTC, pxp9 commented on src/api_traits/async_telegram_api.rs
> +    ) -> Result<MethodResponse<bool>, Self::Error> {
Solve in [Fix comments](https://github.com/ayrat555/frankenstein/pull/85/commits/162f8477c136b3510ed3576cbf436881b603e47b)

2022-08-13 07:35 UTC, pxp9 commented on src/api_params.rs
> +    #[builder(setter(into, strip_option), default=Some(StickerType::Regular))]
Deleted default in [Fix comments](https://github.com/ayrat555/frankenstein/pull/85/commits/162f8477c136b3510ed3576cbf436881b603e47b)

2022-08-13 08:39 UTC, ayrat555 reviewed
looks good just one comment about hiding docs

2022-08-13 08:39 UTC, ayrat555 commented on src/api_traits/telegram_api.rs
> +    fn get_custom_emoji_stickers(
3. Added the method [getCustomEmojiStickers](https://core.telegram.org/bots/api#getcustomemojistickers).

2022-08-13 08:39 UTC, ayrat555 commented on src/objects.rs
> +    pub sticker_type: StickerType,
4. Added the fields type and custom_emoji_id to the class [Sticker](https://core.telegram.org/bots/api#sticker).

2022-08-13 08:39 UTC, ayrat555 commented on src/objects.rs
> +    pub sticker_type: StickerType,
5. Added the field sticker_type to the class [StickerSet](https://core.telegram.org/bots/api#stickerset), describing the type of stickers in the set.

2022-08-13 08:39 UTC, ayrat555 commented on src/objects.rs
> +    #[deprecated(since = "0.19.2", note = "Please use `sticker_type` instead")]
6. The field contains_masks has been removed from the documentation of the class [StickerSet](https://core.telegram.org/bots/api#stickerset). The field is still returned in the object for backward compatibility, but new bots should use the field sticker_type instead.

2022-08-13 08:39 UTC, ayrat555 commented on src/api_params.rs
> +    #[doc(hidden)]
remove this attribute

and add deprecated attribute instead

2022-08-13 08:39 UTC, ayrat555 commented on src/api_params.rs
> +    pub sticker_type: Option<StickerType>,
7. Added the parameter sticker_type to the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).

2022-08-13 08:39 UTC, ayrat555 commented on src/api_params.rs
> +    #[doc(hidden)]
8. The parameter contains_masks has been removed from the documentation of the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).

2022-08-13 08:40 UTC, pxp9 commented on src/api_traits/telegram_api.rs
> +    fn get_custom_emoji_stickers(
Nice :D

2022-08-13 08:40 UTC, pxp9 commented on src/objects.rs
> +    pub sticker_type: StickerType,
Nice :D

2022-08-13 08:41 UTC, pxp9 commented on src/objects.rs
> +    pub sticker_type: StickerType,
Nice :D

2022-08-13 08:50 UTC, pxp9 commented on src/api_params.rs
> +    #[doc(hidden)]
Deprecated and hidden

2022-08-13 08:50 UTC, pxp9 commented on src/objects.rs
> +    #[deprecated(since = "0.19.2", note = "Please use `sticker_type` instead")]
Deprecated and hidden

2022-08-13 08:50 UTC, pxp9 commented on src/api_params.rs
> +    pub sticker_type: Option<StickerType>,
Done :D

2022-08-13 08:52 UTC, ayrat555 approved these changes

2022-08-13 09:05 UTC, merged